### ISSUE TITLE
Fazer validação do Email com Regex

### ISSUE THREAD

**Issue by bruno-azenha** [bruno-azenha/ProjWeb_SCC0219#1]
Vai precisar usar Regex

**Comment by bruno-azenha** [comment]
Esse Regex parece válido:

`<^[a-z][a-z0-9\.\_]+\@[a-z0-9]+\.[a-z]{2,4}$>`

**Comment by Clayton-Oliveira** [comment]
a validação do e-mail está falhando com alguns emails que deveriam ser validos
ex a@a.com

**Comment by bruno-azenha** [comment]
Mudei a RegEx e testei novamente:

![image](https://cloud.githubusercontent.com/assets/7806092/7242719/70ab7fdc-e79b-11e4-95ab-54fd7a6f4526.png)
