### ISSUE TITLE
Fazer Validação do Celular

### ISSUE THREAD

**Issue by bruno-azenha** [bruno-azenha/ProjWeb_SCC0219#10]
Precisa procurar nas propriedades do HTML 5 por uma que permita sugerir o formato do telefone no próprio campo

**Comment by bruno-azenha** [comment]
Extra: Fazer com que os parênteses e hífens apareçam sozinhos

**Comment by Clayton-Oliveira** [comment]
o formato sugerido foi feito com um placeholder
se houver tempo faremos o extra
